wavemaker/docs

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-2-1.md
- learn/wavemaker-release-notes/v10-2-2.md
- website/sidebars.json
Do not merge this yet. We need @vibhus  , @bandhavya to contribute to this PR
> Release notes 10.2.2

- learn/how-tos/implementing-forgot-password-feature-using-java-service.md
- website/sidebars.json
Formatting of java code messed up in learn/how-tos/implementing-forgot-password-feature-using-java-service/ #48
> Formatting fixed for java services 

- learn/app-development/app-security/xss-antisamy-policy-configuration.md
- learn/how-tos/accessing-file-upload-java-code.md
- learn/how-tos/prevent-user-leaving-page-unsaved-changes.md
- website/sidebars.json
1. Added Leaving Page with Unsaved Changes
2. Fixing alignment and missing navigation
> Reported issues

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-2-3.md
- website/sidebars.json
> Release 10-2-3: Initial Notes

- learn/how-tos/intercept-requests-responses-api-calls-one-place.md
- website/sidebars.json
> fixed howtos broken link

- learn/how-tos/intercept-requests-responses-api-calls-one-place.md
- learn/hybrid-mobile/mobile-build-manual.md
- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-2-4.md
- website/sidebars.json
Release notes added and related docs updated.
> Release note 10.2.4

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-2-4.md
Updated release date.
Removed the fix which did not go out with the release. 
Added a new enhancement.
> updated release notes

- learn/app-development/app-security/owasp.md
The script tag code is enclosed in a markdown code fence to render on UI without executing.
> owasp script tag code fence issue #97

- learn/app-development/ui-design/themes.md
- learn/app-development/wavemaker-overview/artifacts-repository.md
- website/sidebars.json
Create theme link is broken in www.wavemaker.com/learn/app-development/ui-design/themes/ #91 
676fa25
Artifact location updated to develop extensions
Fixed broken links in the artifact repository topic including headings
> Artifact doc location update + themes topic links updated

- website/static/css/wavemaker.css
Highlighted the search placeholder text color.
> Algolia DocSearch integrated #46

- website/cypress/integration/basic_spec.js
- website/pages/en/header.js
- website/siteConfig.js
- website/static/css/custom.css
- website/static/js/inject-stylesheets.js
Dynamically appending the navbar dropdown options in the header and is visible in mobile devices and registering click event to show and hide the options dropdown.
> Responsive Nav for Mobile injected dynamically

- website/siteConfig.js
- website/static/css/code-block-buttons.css
- website/static/js/code-block-buttons.js
Fixed https://github.com/wavemaker/docs/issues/111
> copy code button integrated

- learn/app-development/variables/model-variable.md
> Modified addItem method parameters order

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-2-7.md
> release notes 10.2.8 updated

- learn/app-development/ui-design/page-concepts/page-events.md
Updated to multiple actions on a single event.
> Page events

- learn/app-development/widgets/datalive/form/form-field-validator.md
- learn/app-development/widgets/datalive/form/form-fields-configuration.md
- learn/how-tos/synchronizing-java-services-controller.md
- learn/how-tos/synchronizing-wavemaker-apps-ides-beta.md
- learn/hybrid-mobile/mobile-build-manual.md
- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-3-0.md
- website/sidebars.json
Including everything from the 10.3 issues with ticket numbers for easy reference. We can filter from here if they are not relevant. Particularly not sure about the DevOps tickets.
> release notes draft added

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-3-0.md
> Changed 10.3 release date to 31

- learn/app-development/dev-integration/inspection-framework.md
- website/sidebars.json
Adding code blocks 
Adding it to the sidebar in developer options
> inspection framework 

- learn/wavemaker-release-notes.md
Release versions added to the WME release notes.
> wme release notes update

- learn/app-development/widgets/navigation/nav-basic-usage.md
- learn/how-tos/charts-custom-data.md
- learn/how-tos/charts-displaying-user-selection-another-widget.md
- learn/how-tos/charts-handling-dynamic-data.md
- learn/how-tos/tree-use-case-dynamic-tree.md
- learn/how-tos/tree-use-case-java-service.md
- learn/how-tos/tree-use-case-static-variable.md
- learn/how-tos/using-progress-circle-widget.md
- website/sidebars.json
Updated Tree and Nav widget how-to docs sidebar names.
Renamed the charts sidebar names which had repeated Chart keyword. 
Updated code blocks for the Progress Circle widget documentation.
Added Progress circle how-to and feature doc to the sidebar.
> Multiple fixes

- learn/how-tos/scheduling-java-service.md
Updated document to mention that no changes should be done in javaservice_name.spring.xml file instead all changes should be done in project-user-spring.xml file
> Updated project-user-spring.xml file and removed unnecessary slashes

- learn/app-development/services/api-designer/api.md
- learn/app-development/services/api-designer/web-service-apis.md
- learn/app-development/services/creating-backend-services.md
- learn/app-development/variables/data-integration.md
- learn/app-development/variables/web-service.md
- learn/app-development/wavemaker-app-development-faqs/index.md
- website/package-lock.json
- website/sidebars.json
- website/static/css/custom.css
Restructured navigation
Getting started content to studio naming convention
> Cleaning-up sidebar

- learn/wavemaker-release-notes/v10-4-0.md
Removed duplicate entries of WKWebView Upgrade
> Removed duplicate entries of WKWebView Upgrade

- website/blog/2020-04-20-wavemaker-wkwebview-upgrade.md
Title correction and added link to manual build
> Minor corrections

- website/blog/2020-04-20-wavemaker-wkwebview-upgrade.md
Truncated for blog list summary page
> Truncated for blog list summary page

- learn/app-development/deployment/deployment-to-digital-ocean.md
- learn/wavemaker-release-notes/v10-3-0.md
Added new images for DigitalOcean document.
> Release 10.4

- learn/app-development/deployment/deployment-to-digital-ocean.md
Changed the content in the Registry Details section
> DigitalOcean: changes in the Registry details

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-4-0.md
- learn/wavemaker-release-notes/v10-4-1.md
- website/sidebars.json
Release notes for 10.4.1 - in progress.
> release notes 10.4.1

- learn/wavemaker-release-notes/v10-4-1.md
File upload fix moved out of list widget section
> Release Notes 10.4.1: File upload fix moved out of list widget section

- learn/tutorials/build-app-in-5-minutes/app-demo.md
- learn/tutorials/build-app-in-5-minutes/connecting-datasource-to-widget.md
- learn/tutorials/build-app-in-5-minutes/drag-and-drop-widget.md
- learn/tutorials/build-app-in-5-minutes/import-database.md
- learn/tutorials/build-app-in-5-minutes/preview-test-app.md
- website/sidebars.json
Go to the following path to see how it works.
/learn/tutorials/build-app-in-5-minutes/app-demo
> Training courses

- website/siteConfig.js
https://github.com/wavemaker/docs/issues/231 - Fixed
> https://github.com/wavemaker/docs/issues/231 - Fixed

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-4-2.md
Please double-check the bug fix section of the *extra character being added to the data-value of a Text widget*. (line-36)
> Release notes of 10.4.4 added to v10.4.2

- learn/on-premise/architecture.md
- learn/on-premise/aws/install-prerequisites.md
- learn/on-premise/aws/launching-instances-in-aws.md
- learn/on-premise/aws/waveMaker-Enterprise-Setup-on-AWS.md
- learn/on-premise/azure/install-prerequisites.md
- learn/on-premise/azure/launching-instances-in-azure-vhd.md
- learn/on-premise/azure/launching-instances-in-azure.md
- learn/on-premise/azure/wavemaker-enterprise-setup-on-azure.md
- learn/on-premise/configure/add-apps-capacity.md
- learn/on-premise/configure/add-dev-capacity.md
- learn/on-premise/configure/config-ssl.md
- learn/on-premise/gcp/install-prerequisites.md
- learn/on-premise/gcp/launching-instances-in-gcp.md
- learn/on-premise/gcp/wavemaker-enterprise-setup-on-gcp.md
- learn/on-premise/getting-started.md
- learn/on-premise/hyper-v/install-prerequisites.md
- learn/on-premise/hyper-v/launching-instances-in-hyper-v-vhd.md
- learn/on-premise/hyper-v/wavemaker-enterprise-setup-on-hyperv.md
- learn/on-premise/prerequisites.md
- learn/on-premise/vmware-esxi/install-prerequisites.md
- learn/on-premise/vmware-esxi/launching-instances-in-esxi-iso.md
- learn/on-premise/vmware-esxi/launching-instances-in-esxi-ova.md
- learn/on-premise/vmware-esxi/wavemaker-enterprise-setup-on-vmware.md
- learn/on-premise/welcome.md
- website/sidebars.json
> Wme setup non privileged

- learn/on-premise/aws/install-prerequisites.md
- learn/on-premise/azure/install-prerequisites.md
- learn/on-premise/configure/add-apps-capacity.md
- learn/on-premise/configure/add-dev-capacity.md
- learn/on-premise/configure/config-ssl.md
- learn/on-premise/gcp/install-prerequisites.md
- learn/on-premise/hyper-v/install-prerequisites.md
- learn/on-premise/vmware-esxi/install-prerequisites.md
> Fixing markdown lint issues

- learn/app-development/ui-design/creating-themes.md
- website/blog/2020-06-01-build-themes-without-any-coding.md
Fix the broken links for the step images
> Modified the image sources

- amplify.yml
- learn/app-development/build-options-app-deployment.md
- learn/app-development/dev-integration/inspection-framework.md
- learn/app-development/services/database-services/working-with-databases.md
- learn/app-development/widgets/chart/onbeforerender.md
- learn/on-premise/aws/install/download-copy-installer.md
- learn/on-premise/aws/install/setup-using-cw.md
- learn/on-premise/azure/install/download-copy-installer.md
- learn/on-premise/azure/install/setup-using-cw.md
- learn/on-premise/gcp/install/download-copy-installer.md
- learn/on-premise/gcp/install/setup-using-cw.md
- learn/on-premise/hyper-v/install/download-copy-installer.md
- learn/on-premise/hyper-v/install/setup-using-cw.md
- learn/on-premise/prerequisites.md
- learn/on-premise/upgrade/download-copy-patch.md
- learn/on-premise/vmware-esxi/install/download-copy-installer.md
- learn/on-premise/vmware-esxi/install/setup-using-cw.md
- website/.textlintrc
- website/package-lock.json
- website/package.json
We are using https://github.com/textlint/textlint for text linting with the rule - https://github.com/sapegin/textlint-rule-terminology
Added **WaveMaker** to the .textlintrc config file unders terms array for verification
If there is any mismatch we will see the following kind of error
```
/docs/learn/app-development/build-options-app-deployment.md
14:39  ✓ error  Incorrect usage of the term: “wavemaker”, use “WaveMaker” instead  terminology
/docs/learn/app-development/dev-integration/inspection-framework.md
507:33  ✓ error  Incorrect usage of the term: “wavemaker”, use “WaveMaker” instead  terminology
535:33  ✓ error  Incorrect usage of the term: “wavemaker”, use “WaveMaker” instead  terminology
```
> Branding lint

- learn/how-tos/integrating-sample-jasper-report-wavemaker-application.md
updated the if condition to close the database connection
> updated the if condition to close the database connection

- learn/wavemaker-release-notes/v10-5-0.md
- website/blog/2020-06-24-wavemaker-mobile-filepicker.md
Added blog on file picker plugin.
> Added blog on file picker plugin.

- website/blog/2020-06-24-wavemaker-mobile-filepicker.md
added link to how to create a mobile app
> added link to how to create a mobile app

- learn/on-premise/architecture.md
- learn/on-premise/aws/install-prerequisites.md
- learn/on-premise/aws/install/apply-license.md
- learn/on-premise/aws/launching-instances-in-aws.md
- learn/on-premise/aws/waveMaker-Enterprise-Setup-on-AWS.md
- learn/on-premise/azure/install-prerequisites.md
- learn/on-premise/azure/launching-instances-in-azure-vhd.md
- learn/on-premise/azure/launching-instances-in-azure.md
- learn/on-premise/configure/add-apps-capacity.md
- learn/on-premise/configure/add-dev-capacity.md
- learn/on-premise/configure/config-ssl.md
- learn/on-premise/gcp/install-prerequisites.md
- learn/on-premise/gcp/launching-instances-in-gcp.md
- learn/on-premise/getting-started.md
- learn/on-premise/hyper-v/install-prerequisites.md
- learn/on-premise/hyper-v/launching-instances-in-hyper-v-vhd.md
- learn/on-premise/prerequisites.md
- learn/on-premise/users-roles.md
- learn/on-premise/vmware-esxi/install-prerequisites.md
- learn/on-premise/vmware-esxi/launching-instances-in-esxi-iso.md
- learn/on-premise/vmware-esxi/launching-instances-in-esxi-ova.md
- learn/on-premise/welcome.md
- website/sidebars.json
we changed the external instance name to StudioWorkspace Instance / AppDeployment Instance. presently we are looking to go with changes if any changes are will do next PR
> Wme new changes for external instance name changes

- learn/hybrid-mobile/mobile-build-manual.md
Instead of xcodeproj, use xcworkspace
> Instead of xcodeproj, use xcworkspace

- learn/app-development/app-security/authentication.md
The constructor was incorrect and modified in the doc as per the WMUser object.
> minor doc change for authentication.md file

- learn/app-development/widgets/form-widgets/chips.md
updated item.datavalue to item.value
> updated item.datavalue to item.value

- website/blog/2020-06-24-wavemaker-mobile-filepicker.md
Updated document about the cause of increase of size of IPA.
> Updated document about the cause of increase of size of IPA.

- website/blog/2020-06-24-wavemaker-mobile-filepicker.md
> minor correction

- learn/app-development/app-security/authentication.md
Added the step to provide the redirect URL for the deployed application outside the wavemaker.
> Added the step for OpenId redirect url

- learn/wavemaker-release-notes/v10-5-6.md
> updated mobile changes

- learn/app-development/app-security/session-persistence.md
- learn/wavemaker-release-notes/v10-6-0.md
- website/blog/2020-12-08-wavemaker-release-10-6-version.md
> WaveMaker 10.6 blog

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-6-1.md
- website/sidebars.json
> release notes

- learn/app-development/services/java-services/java-integration-database-service.md
- learn/app-development/services/java-services/java-integration-services.md
- website/sidebars.json
This doc is updated on how to use findAll method and the value that query param expects
> Updated JavaService integration with Database services

- learn/wavemaker-known-issues.md
- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-6-4.md
- website/sidebars.json
Release notes 10.6.4
Update release page
Update known issues
> release notes 10.6.4

- learn/wavemaker-known-issues.md
Removed HQL Exception issue as this is working as expected as per design.
Added another regression issue to the list and modified the expected to fix by version.
> removed one issue and added another

- learn/how-tos/custom-security-using-google-oauth-prefab.md
- website/package-lock.json
Google prefabs i changed in last days. I updated the import from org.springframework.social. and pom.xml dependencies are now the latest to use from updated maven repo.
> Hi i wrote the new guide on how to ember the google prefab

- learn/how-tos/integrating-junit-tests-for-wavemaker-application.md
- website/package-lock.json
- website/sidebars.json
Added a new doc regarding integrating JUnit tests with WaveMaker application.
> Added doc for JUnit tests integration in WaveMaker app

- learn/how-tos/integrating-junit-tests-for-wavemaker-application.md
Made few changes to the Java service file and added a new header
> Updated the JUnit doc

- learn/wavemaker-release-notes/v10-7-0.md
Updated log4j library to log4j2
> Update Log4j2 library name

- learn/app-development/deployment/deployment-to-azure.md
Please make sure your Azure subscription should allow launching an instance with Standard_A1, Standard_A2, and Standard_A3
> Updated note to have

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v10-7-1.md
- website/sidebars.json
> Release 10.7.1

- website/static/js/inject-stylesheets.js
updated the feed url to the new one https://docs.wavemaker.com/learn/blog/feed.xml
> updated the feed url to the new one

- learn/how-tos/sso-openid-azure-active-directory.md
Updated as  **Client Secret** Value and provided Microsoft link to create the Azure App Client Secret value.
> Modified for ticket WM-20064

- learn/hybrid-mobile/use-push-notification-wm-mobile-app.md
Updated ‘phonegap-plugin-push’ plugin URL with latest commit id.
> Updated the latest Push Plugin URL

- learn/how-tos/using-cordova-plugins.md
added var to the script variable to define
> fixed variale undefined issue

- learn/app-development/widgets/prefab/entity-extraction-from-documents.md
fixed links to download  prefab and how to import prefab
> fixed links

- website/blog/2021-09-01-angular-10-update.md
Added just the basic details. Need more details about the docker image.
> Angular 10 update blog

- learn/app-development/services/database-crud-event-listeners.md
- learn/how-tos/audit-history-using-crud-listeners.md
- learn/how-tos/custom-business-logic-using-crud-event-listeners.md
- learn/how-tos/validations-using-crudListeners.md
- learn/wavemaker-release-notes/v10-9-0.md
- learn/wavemaker-release-notes/v10-9-1.md
- learn/wavemaker-release-notes/v10-9-2.md
1. Angular version update
2. CRUD Listener use cases referencing
> Multiple: 10.9 stack update + crud listener use cases referencing

- learn/hybrid-mobile/use-push-notification-wm-mobile-app.md
Updated the push plugin latest Url
> Updated the push plugin latest Url

- website/blog/2021-12-17-angular-11-update.md
This is a draft copy. We can explain more about what to test and what to expect.
> blog on angular 11 update

- learn/wavemaker-release-notes/v10-11-0.md
Another PR because the build failed.
> Release v10-11-0 

- learn/app-development/dev-integration/chrome-developer-tool.md
Included WaveMaker Devtool extension installation link
> Added WaveMaker Devtool installation link

- learn/app-development/services/api-mock-server.md
Updated server url from http to https and removed note
> Updated APIMock server doc

- learn/react-native/react-native.md
- learn/react-native/supported-variables.md
1. Removed media links
2. Variable support page set format
> React Native docs

- learn/app-development/deployment/deployment-overview.md
Corrected the spelling of Automation
> Corrected spelling

- learn/enterprise-release-notes.md
- learn/wavemaker-release-notes.md
- website/sidebars.json
WMO and WME release information organized separately in a grid format.
> Organizing WMO and WME releases

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v11-1-0.md
Adding a few more bug fixes, library updates, and more #628
> WaveMaker 11 GA - release

- learn/app-development/sspa/micro-frontend.md
Made changes to the doc as per the latest changes made in the sspa cli command line and added description for each parameter
> Changes to SSPA doc as per the latest changes

- learn/app-development/sspa/micro-frontend.md
added node version and note specific to parameter
> added node version and note specific to parameter

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v11-1-0.md
Updated note on sspa cli fix for WM 11.x projects
> Updated note on sspa cli fix

- learn/wavemaker-release-notes.md
- learn/wavemaker-release-notes/v11-0-1.md
- learn/wavemaker-release-notes/v11-0-2.md
- learn/wavemaker-release-notes/v11-0-3.md
- learn/wavemaker-release-notes/v11-1-0.md
- learn/wavemaker-release-notes/v11-1-1.md
- learn/wavemaker-release-notes/v11-1-2.md
- learn/wavemaker-release-notes/v11-1-3.md
- learn/wavemaker-release-notes/v11-2-0.md
- learn/wavemaker-release-notes/v11-2-1.md
- learn/wavemaker-release-notes/v11-2-2.md
Release notes PR details: 
**11 beta** #607 
**11 GA** #628 
**11.2** #664
> Updated libraries: jquery, jquery-ui and lodash

- learn/wavemaker-release-notes.md
Only a single issue - so I added it to the release grid only.
> Release - 11.2.3

- website/blog/2023-08-14-aa-compliance-accessibility.md
This is the first version of this copy, we will add lot more details and links to release versions of different ADA fixes.
> AA Compliant Website Accessibility through Wavemaker Platform

- learn/how-tos/add-custom-filters.md
- learn/how-tos/customizing-post-authentication-handlers.md
- learn/how-tos/twilio-otp-integration.md
- learn/howtos-documents.md
- website/sidebars.json
Added custom filter docs in how-tos and introduced @Order for authenticationSuccessHandler
> Added custom filter docs in how-tos and introduced @Order for authenticationSuccessHandler

- learn/how-tos/customize-breakpoints-for-widths-of-show-in-devices.md
- website/blog/2024-01-22-charting-libraries-d3-nvd3-upgrade.md
- website/static/js/inject-stylesheets.js
Added key changes in d3 v7 version and its comparison with d3 v3
> D3 and Nvd3 libraries upgrade documentation

- website/blog/2024-03-04-wavemaker-11.6-release.md
Blog: Update hyperlink to point to bottom of the page for better usability
> Blog: Update hyperlink to point to bottom of the page for better usability

- learn/react-native/styles.md
> Fix broken link #886

- learn/app-development/wavemaker-overview/product-walkthrough.md
> Broken link #821
